@startuml

skinparam linetype ortho

left to right direction

entity "User" as User {
    *id: long <<generated>>
    ---
    name: string
    email: string
    password: string
    image: string
    gender: byte
    birthday: date
    phone: string
    city: string
    country: string
    address: string
    role: string <<enum>>
    'guest, member, admin
    created_at: datetime
    last_login_at: datetime
}

entity "Product" as Product {
    *id: Long <<generated>>
    ---
    promotion_id: long <<FK>>
    category_id: long <<FK>>
    name: string
    price: int
    image_url: string
    in_stock: int
    rating: double
    sold_count: int
    short_description: string
}
entity "CartItem" as CartItem {
    *id: long <<generated>>
    ---
    cart_id: long <<FK>>
    product_id: long <<FK>>
    quantity: int <<non-negative>>
    unit_price: int
}

entity "Cart" as Cart {
    *id: long <<generated>>
    ---
    user_id: long <<FK>>
    quantity: int <<non-negative>>
    unit_price: int
    status: string <<enum>>
    'ACTIVE, CHECKED_OUT, ABANDONED
    created_at: datetime
    updated_at: datetime
}

entity "Order" as Order {
    *id: long <<generated>>
    ---
    user_id: long <<FK>>
    order_number: string
    status: string <<enum>>
    'PENDING, PAID, CANCELLED, SHIPPED, COMPLETED
    payment_method: string <<enum>> 
    'CREDIT_CARD, PAYPAL
    is_paid: boolean
    paid_at: datetime <<nullable>>
    cancelled_at: datetime <<nullable>>
    shipping_method: string <<enum>>
    'STANDARD, EXPRESS
    shipping_address: string
    shipping_status: string <<enum>>
    'PENDING, IN_TRANSIT, DELIVERED
    total_price: int <<calculated>>
    created_at: datetime
    updated_at: datetime
}

entity "OrderItem" as OrderItem{
    *id: long <<generated>>
    ---
    order_id: long <<FK>>
    product_id: long
    product_name: string
    quantity: int <<non-negative>>
    unit_price: int
    total_price: int <<calculated>>
}

entity "Promotion" as Promotion {
    *id: long <<generated>>
    ---
    name: string
    disconutType: string <<enum>>
    'PERCENTAGE, FIXED_AMOUNT
    disconutValue: int
    description: string <<nullable>>
    imageUrl: string
    is_active: boolean
    start_date: date
    end_date: date
}

entity "Payment" as Payment {
    *id: long <<generated>>
    ---
    order_id: long <<FK, unique>>
    payment_method: string <<enum>> 
    'CREDIT_CARD, PAYPAL, BANK_TRANSFER
    status: string <<enum>>
    'PENDING, COMPLETED, FAILED
    amount: int 
    transaction_id: string <<nullable>>
    created_at: datetime
    updated_at: datetime
}

entity "Category" as Category {
    *id: long <<generated>>
    ---
    name: string
    description: string <<nullable>>
}

entity "Tag" as Tag{
    *id: long <<generated>>
    ---
    name: string
}
entity "ProductTag" as ProductTag {
    *product_id: long <<FK>>
    *tag_id: long <<FK>>
}

entity "Token" as Token {
    *id: long <<generated>>
    ---
    user_id: long <<FK>>
    token: string <<unique>>
    token_type: string <<enum>>
    'forgetPassword, emailVerification
    used: boolean <<default false>>
    created_at: datetime
    expires_at: datetime
}

Tag }|--|{ ProductTag
ProductTag }|--|| Product
Cart }|--|| User
Cart ||--|{ CartItem
CartItem }|--|| Product
Order }|--|| User
Order ||--|{ OrderItem
Product }|--|| Promotion
Product }|--|| Category
Payment ||--|| Order
Token }|--|| User
@enduml